### ISSUE TITLE
work experience, header section, texts are not wrapped

### ISSUE THREAD

**Issue by WangYBeHappy** [GitChow/PrintNicely#2]
Hi,

When I use this plugin, I found that some words came in an unexpected way. Please see the attachment.
<img width="561" alt="screen shot 2016-08-24 at 12 32 16 am" src="https://cloud.githubusercontent.com/assets/21115910/17900678/ac2a6d78-6992-11e6-931e-758f92b1c5ba.png">

**Comment by GitChow** [comment]
fixed, wrapped header section to 33% width
